version: "2"
services:
  transmiision:
    image: "linuxserver/transmission"
    ports:
      - "80:9091"
      - "51413:51413"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    stdin_open: true
    tty: true
